name: Azure Login
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  azlogin:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: Azure/Login@v1
        with:
         creds: ${{ secrets.AZURE_CREDENTIALS }}
