name: Backup Entire Site to Azure on Master Push
on:
  push:
    branches: [ master ]
jobs:
  firewallAllow:
    runs-on: ubuntu-latest
    steps:
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - run: | 
          az storage account update --resource-group ${{ secrets.AZURE_STORAGE_RG }} --name ${{ secrets.AZURE_STORAGE_NAME }} --default-action Allow  
  uploadToAzure:
    runs-on: ubuntu-latest
    needs: firewallAllow
    steps:
      - uses: actions/checkout@v2
      - uses: bacongobbler/azure-blob-storage-upload@v1.0.0
        with:
          source_dir: "./"
          container_name: "${{ secrets.container_name }}"
          connection_string: "${{ secrets.connection_string }}"
  firewallDeny:
    runs-on: ubuntu-latest
    needs: uploadToAzure
    steps:
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - run: | 
          az storage account update --resource-group ${{ secrets.AZURE_STORAGE_RG }} --name ${{ secrets.AZURE_STORAGE_NAME }} --default-action Deny
