name: Backup Entire Site to Azure on Master Push
on:
  push:
    branches: [ master ]
jobs:
  firewallAllow:
    runs-on: ubuntu-latest
    steps:
      - uses: jesseloudon/azure-storage-firewall-default-action@v1.0
        with:
          sp_client_id: ${{ secrets.sp_client_id }}
          sp_client_secret: ${{ secrets.sp_client_secret }}
          tenant_id: ${{ secrets.tenant_id }}
          resourcegroup_name: "github-rg"
          storageaccount_name: ${{ secrets.AZURE_STORAGE_NAME }}
          configure_firewall_default_action: "Allow"
  uploadToAzure:
    runs-on: ubuntu-latest
    needs: firewallAllow
    steps:
      - uses: actions/checkout@v2
      - uses: bacongobbler/azure-blob-storage-upload@v1.0.0
        with:
          source_dir: "./"
          container_name: "${{ secrets.container_name }}"
          connection_string: "${{ secrets.connection_string }}"
  firewallDeny:
    runs-on: ubuntu-latest
    needs: uploadToAzure
    steps:
      - uses: jesseloudon/azure-storage-firewall-default-action@v1.0
        with:
          sp_client_id: ${{ secrets.sp_client_id }}
          sp_client_secret: ${{ secrets.sp_client_secret }}
          tenant_id: ${{ secrets.tenant_id }}
          resourcegroup_name: "github-rg"
          storageaccount_name: ${{ secrets.AZURE_STORAGE_NAME }}
          configure_firewall_default_action: "Deny"
