name: Backup Entire Site to Azure on Master Push
on:
  push:
    branches: [ master ]
jobs:
  firewall:
    runs-on: ubuntu-latest
    steps:
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: jesseloudon/azure-storage-firewall-default-action-0.1
        with:
          resourcegroup_name: "github-rg"
          storageaccount_name: "aeblogstorage"
          configure_firewall_default_action: "Allow"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bacongobbler/azure-blob-storage-upload@v1.0.0
        with:
          source_dir: "./"
          container_name: "${{ secrets.container_name }}"
          connection_string: "${{ secrets.connection_string }}"
